baseURL = "https://bacxiunho.github.io/"
languageCode = "en-us"
title = "Bạc Xỉu Nhỏ"
theme = "hugo-theme-yinyang"

[params]
    author = "Bạc Xỉu Nhỏ"
    description = "Bạc Xỉu Nhỏ - Siêu Nhân Nước Suối"
    images = ["vien-dang.jpg"]
    title = "Bạc Xỉu Nhỏ"
    og_image = "vien-dang.jpg"